# default profile
logging:
  level:
    '[com.doding]': debug
  pattern:
    console: '%clr(%d{MM:dd:ss} [%-5level] %c{36}.%M%L -%m%n)'

spring:
  output:
    ansi:
      enabled: ALWAYS
---
spring:
  config:
    activate:
      on-profile:
        - oper # oper profile
server:
  db:
    ip: 192.168.0.1
    user: admin
---
spring:
  config:
    activate:
      on-profile:
        - dev # dev profile
server:
  db:
    ip: 192.168.0.9
    user: test
logging:
  level:
    '[com.doding]': trace
